[project]
name = "sgbm"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "pillow>=11.2.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
